services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmer123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: mnck/sdc-backend:latest
    container_name: springboot
    ports:
      - "2025:2085"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    image: mnck/sdc-frontend:latest
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  mysql_data: